server:
  port: 8081

spring:
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/fitness_user_db}
    username: ${USER_DB_USERNAME:postgres}
    password: ${USER_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

keycloak:
  admin:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8181}
    realm: ${KEYCLOAK_REALM:fitness-oauth2}
    auth-realm: ${KEYCLOAK_AUTH_REALM:master}
    client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:}
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
    grant-type: ${KEYCLOAK_GRANT_TYPE:password}
